replicaCount: 1

image:
  repository: amaurya07/short_url
  pullPolicy: IfNotPresent
  tag: "0c77e0885b17117ba9253f36a46a71af3c3c5a53"

serviceAccount:
  create: false
  annotations: {}
  name: ""

service:
  type: NodePort
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: 
  limits:
    cpu: "128m"
    memory: "500Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

nodeSelector: {}
